class Faye::Hazelcast::EventsListener
  include com.hazelcast.core.MessageListener

  def initialize(engine)
    @engine = engine
  end

  # Process events generated by the cluster
  #
  # An action on node 1 could be relevant for a connection handled by node 2,
  # so we route these events through a global topic to ensure all nodes see it.
  def onMessage(event)
    type, client_id = event.getMessageObject().split(':')
    case type
    when 'message'
      @engine.empty_queue(client_id)
    when 'disconnect'
      @engine.server.trigger(:close, client_id)
    else
      @engine.server.debug 'Unknown event ?', type
    end
  end
end
